language: go
go:
  - 1.7
  - tip
env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows
install:
  - go get github.com/golang/go/src/cmd/vet
  - go get -v github.com/jonaswouters/goclerk
script:
  - go build
  - go fmt ./...
  - go vet ./...